remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme@master
plugins:
- jekyll-remote-theme

title: Fantasy Creatures Classifier
description: An image classification API the classify 30 different types of fantasy creatures.

author:
  name: Md. Abidul Mohaimin