remote_theme: pages-themes/architect@main
plugins:
- jekyll-remote-theme

title: Fantasy Creatures Clssifier
description: An image classification API the classify 30 different types of fantasy creatures.

author:
  name: Md. Abidul Mohaimin