remote_theme: JustGoodThemes/Scriptor-Jekyll-Theme@master
plugins:
  - jekyll-remote-theme

title: Tittle YML
description: An image classification API that classifies 30 different types of fantasy creatures.

author:
  name: Md. Abidul Mohaimin

navigation:
  - text: Home
    url: /
  - text: Test The Classifier 
    url: /fantasy_creatures_classifier.html
